---
- name: Trabajar con ficheros
  hosts: centos

  tasks:
  - name: Crear un fichero vacio
    file:
      path: "/tmp/prueba.txt"
      state: "touch"

  - name: Borrar el fichero anterior
    file:
      path: "/tmp/prueba.txt"
      state: "absent"