---
- name: Prueba con variables FACT
  hosts: centos
  
  tasks:
  - name: Ver variables FACT
    debug:
      msg: "Arquitectura {{ansible_facts['architecture']}} {{ansible_facts['bios_vendor']}} {{ansible_facts['all_ipv4_addresses'][1]}}"

  - name: Usar diccionarios FACT
    debug:
      var: ansible_facts.date_time.day